version: 2.1

orbs:
  sonarqube: clicklogiq/sonarqube@1.0.1

defaults: &defaults
  working_directory: ~/ds-mobile
  docker:
    - image: circleci/node:14

jobs:
  lint:
    <<: *defaults
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - run: yarn run lint
      - run: yarn run format

  test_node_14:
    <<: *defaults
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - run: yarn run test -u

  release:
    <<: *defaults
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      # Run optional required steps before releasing
      # - run: npm run build-script
      - run: npx semantic-release

workflows:
  version: 2
  test_and_release:
    # Run the test jobs first, then the release only when all the test jobs are successful
    jobs:
      - lint
      - test_node_14:
          requires:
            - lint
      - release:
          filters:
            branches:
              only:
                - master
                - beta
          requires:
            - lint
            - test_node_14
